version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://agents-platform.ngrok.io/webhook/
      - GENERIC_TIMEZONE=America/New_York
      - N8N_PATH=/n8n
      - N8N_METRICS=true
      - N8N_LOG_LEVEL=info
      - N8N_LOG_OUTPUT=console
      - EXECUTIONS_PROCESS=main
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=true
      - N8N_DIAGNOSTICS_ENABLED=false
    volumes:
      - /root/n8n-data:/home/node/.n8n
      - /root/n8n-data/transactions:/data/transactions
      - /root/n8n-data/backups:/data/backups
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  web:
    image: nginx:alpine
    container_name: web-server
    restart: unless-stopped
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - n8n

  ngrok:
    image: ngrok/ngrok:alpine
    container_name: ngrok
    restart: unless-stopped
    command: 
      - "http"
      - "web-server:80"
      - "--domain=agents-platform.ngrok.io"
      - "--log-level=info"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "127.0.0.1:4040:4040"
    depends_on:
      - web

networks:
  default:
    driver: bridge      